{{- if and (eq .Values.ingress.tls.mode "cert-manager") .Values.ingress.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    {{- with deepCopy .Values.annotations | merge (default dict .Values.ingress.tls.certificate.annotations) }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.name" . | quote }}
spec:
  commonName: {{ .Values.ingress.hosts | first | quote }}
  dnsNames:
    {{- toYaml .Values.ingress.hosts | nindent 4 }}
  issuerRef:
    kind: Issuer
    name: {{ include "chart.name" . | quote }}
  secretName: {{ include "ingress.secret" . | quote }}
{{- end }}
