{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with deepCopy .Values.annotations | merge (default dict .Values.ingress.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "chart.name" . | quote }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "play.name" $ | quote }}
                port:
                  number: {{ $.Values.play.ports.http | int }}
            path: /
            pathType: Prefix
  {{- end }}
  {{- if eq .Values.ingress.tls.mode "cert-manager" }}
  tls:
    - hosts:
        {{- toYaml .Values.ingress.hosts | nindent 8 }}
      secretName: {{ include "ingress.secret" . | quote }}
  {{- end }}
  {{- if eq .Values.ingress.tls.mode "secret" }}
  tls:
    - hosts:
        {{- toYaml .Values.ingress.hosts | nindent 8 }}
      secretName: {{ .Values.ingress.secret | quote }}
  {{- end }}
{{- end }}
