apiVersion: v1
kind: ConfigMap
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "play.labels" . | nindent 4 }}
  name: {{ include "play.name" . | quote }}
data:
  server.yml: |-
    # Server configuration.
    server:
      # Address to listen for incoming HTTP requests.
      http: ":{{ .Values.play.ports.http | int }}"

    # Configuration of the sandbox environment.
    sandbox:
      # Configuration of the jupyter kernels.
      kernels:
        {{- range .Values.kernels }}
        - name: {{ .name | quote }}
          {{- with .init }}
          init: {{ $.Files.Get . | quote }}
          {{- end }}
          jupyter:
            url: "http://{{ include "jupyter.name" $ }}:{{ $.Values.jupyter.ports.http | int }}"
            token: ckhub
          kernel: {{ .kernel | quote }}
          limit: {{ div .limit $.Values.play.replicas | int }}
        {{- end }}
