{{- if and .Values.play.serviceAccount .Values.play.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with deepCopy .Values.annotations | merge (default dict .Values.play.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "play.labels" . | nindent 4 }}
    {{- with .Values.play.serviceAccount.labels -}}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "play.serviceAccount" . | quote }}
{{- end }}
