apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": {{ include "chart.name" . | quote }}}'
  {{- with deepCopy .Values.annotations | merge (default dict .Values.play.service.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- with .Values.play.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "play.name" . | quote }}
spec:
  ports:
    - name: http
      port: {{ .Values.play.ports.http | int }}
      protocol: TCP
      targetPort: {{ .Values.play.ports.http | int }}
  selector:
    {{- include "play.selector" . | nindent 4 }}
  type: NodePort
