apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ckhub.name" . | quote }}
  labels:
    {{- include "ckhub.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  server.yml: |-
    # Server configuration.
    server:
      # Address to listen for incoming HTTP requests.
      http: ":{{ .Values.ckhub.ports.http | int }}"

    # Configuration of the sandbox environment.
    sandbox:
      # Configuration of the jupyter kernels.
      kernels:
        {{- $files := .Files }}
        {{- range .Values.sandbox.kernels }}
        - name: {{ .name | quote }}
          {{- with .init }}
          init: {{ $files.Get . | quote }}
          {{- end }}
          jupyter: {{- toYaml .jupyter | nindent 12 }}
          kernel: {{ .kernel | quote }}
          limit: {{ default 5 .limit | int }}
        {{- end }}
