{{- if and .Values.image.pullSecret .Values.image.pullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckhub.image.pullsecret" . | quote }}
  labels:
    {{- include "ckhub.labels" . | nindent 4 }}
    {{- with .Values.image.pullSecret.labels -}}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with deepCopy .Values.annotations | merge (default dict .Values.image.pullSecret.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "ckhub.image.credentials" . | quote }}
{{- end }}
